// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_IkJmuph2xX_czigdksTL9blHsh-1qto',
    appId: '1:952921194402:web:e16b45fcafb135cbe87cfb',
    messagingSenderId: '952921194402',
    projectId: 'bloodbank31-6cbc0',
    authDomain: 'bloodbank31-6cbc0.firebaseapp.com',
    storageBucket: 'bloodbank31-6cbc0.appspot.com',
    measurementId: 'G-NS0CS3YGZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9xM6tkJTHm6mJiijKWQDqUFjuoIUx2fU',
    appId: '1:952921194402:android:43f1625dbae2098ee87cfb',
    messagingSenderId: '952921194402',
    projectId: 'bloodbank31-6cbc0',
    storageBucket: 'bloodbank31-6cbc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSzsT_3SmPbMos1QBWwiZ_wnjzaDJpgkA',
    appId: '1:952921194402:ios:c954b54e0b1481fee87cfb',
    messagingSenderId: '952921194402',
    projectId: 'bloodbank31-6cbc0',
    storageBucket: 'bloodbank31-6cbc0.appspot.com',
    iosClientId:
        '952921194402-o31bk6si3cc48meetj4jig02slffb8am.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodbankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSzsT_3SmPbMos1QBWwiZ_wnjzaDJpgkA',
    appId: '1:952921194402:ios:c954b54e0b1481fee87cfb',
    messagingSenderId: '952921194402',
    projectId: 'bloodbank31-6cbc0',
    storageBucket: 'bloodbank31-6cbc0.appspot.com',
    iosClientId:
        '952921194402-o31bk6si3cc48meetj4jig02slffb8am.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodbankApp',
  );
}
